const CONSTANT = {
  MAX_CAR_NAME_LENGTH: 5,
  MAX_RANDOM_NUMBER: 9,
  MIN_RANDOM_NUMBER: 0,
  MIN_MOVEMENT_CONDITION_NUMBER: 4,
  BLANK: '',
  START_ROUND: 0,
  GAME_ROUND_CONDITION: /[^\d]/,
  CAR_NAME_CONDITION: /[^a-zA-Z0-9가-힣ㄱ-ㅎ]/g,
  CAR_NAME_SEPARATOR: ',',
};
export default CONSTANT;
