export const CONDITIONS = Object.freeze({
  EMPTY_STRING: "",
  MAX_CAR_NAME_LENGTH: 5,
  MIN_CAR_COUNT: 2,
  MIN_ROUND_COUNT: 1,
  INITIAL_POSITION: 0,
  INITIAL_ROUND: 0,
  MIN_RANDOM_NUM: 0,
  MAX_RANDOM_NUM: 9,
  MIN_NUM_TO_MOVE: 4,
  NEW_LINE: "\n",
});
