export const CONFIG = Object.freeze({
  CAR_MOVE_DISTANCE: 1,
  MIN_CAR_LIST_LENGTH: 2,
  MIN_CAR_NAME_LENGTH: 1,
  MAX_CAR_NAME_LENGTH: 5,

  CAR_MOVING_CONDITION: 4,
  MIN_RANDOM_NUMBER: 1,
  MAX_RANDOM_NUMBER: 9,

  MIN_TURN_COUNT: 1,
  MAX_TURN_COUNT: 10,
});
