export const SERVICE_CONSTSANSTS = Object.freeze({
  DELIMITER: ',',
  MINIMAL_CAR_NAME_LENGTH: 1,
  MAXIMAL_CAR_NAME_LENGTH: 5,
  MINIMAL_CAR_COUNT: 2,
  MOVING_REFERENCE_NUMBER: 4,
  MOVING_INDICATOR: '-',
});

export const ERROR_PREFIX = '[ERROR]';
