export const ERROR_MESSAGE_DEFAULT = "[ERROR]";
export const ERROR_MESSAGE_CAR_NAME_OVER_FIVE = `${ERROR_MESSAGE_DEFAULT} 길이가 5 미만의 자동차 이름을 입력해주세요.`;
export const ERROR_MESSAGE_NOT_INTEGER = `${ERROR_MESSAGE_DEFAULT} 정수를 입력해주세요.`;
export const ERROR_MESSAGE_NOT_POSITIVE_POSITIVE = `${ERROR_MESSAGE_DEFAULT} 양수를 입력해주세요.`;
export const ERROR_MESSAGE_NOT_NUMBER = `${ERROR_MESSAGE_DEFAULT} 숫자를 입력해주세요.`;
